apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-application
  template:
    metadata:
      labels:
        app: first-application
    spec:
      containers:
      - name: first-application
        image: vijaythirumalareddy335/first-application:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: first-application
spec:
  selector:
    app: first-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
